### ISSUE TITLE
Is it possible to run these benchmarks on Android?

### ISSUE THREAD

**Issue by st3fan** [evolvedbinary/jni-benchmarks#2]
I think it would be really interesting to see how these tests behave on Android with Dalvik. I'm curious if they are portable to that platform.

**Comment by adamretter** [comment]
Hi @st3fan I haven't tried to be honest. I think most of the code if not all should he portable.

I'd welcome a PR if changes are needed for compatibility, but I don't have the time or need to try it myself at the moment.
